## Start with special matrix using numpy and scipy.linalg

In [4]:
import numpy as np
import scipy.linalg as alg
a = np.array([[1,-1,0],[-1,1,-1],[0,-1,1]])
print(a)


[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
