## Start with special matrix using numpy and scipy.linalg

In [1]:
import numpy as np
import scipy.linalg as alg


### 四种特殊矩阵的生成程序
&emsp;&emsp;首先生成n * n的一维zero数组，然后按照index赋值，仅需要检查最后赋值不越界

In [2]:
def KTBC(Type,n):
    mat = np.zeros(n*n)
    if Type == "K":
        for i in range(n):
            if i <n-1:
                mat[(n+1)*i-1] = -1
                mat[(n+1)*i] = 2
                mat[(n+1)*i+1]=-1
            else:
                mat[(n+1)*i-1] = -1
                mat[(n+1)*i] = 2
    elif Type == "T":
        for i in range(n):
            if i <n-1:
                mat[(n+1)*i-1] = -1
                mat[(n+1)*i] = 2
                mat[(n+1)*i+1]=-1
            else:
                mat[(n+1)*i-1] = -1
                mat[(n+1)*i] = 2
        mat[0]=1
    elif Type == "T":
        for i in range(n):
            if i <n-1:
                mat[(n+1)*i-1] = -1
                mat[(n+1)*i] = 2
                mat[(n+1)*i+1]=-1
            else:
                mat[(n+1)*i-1] = -1
                mat[(n+1)*i] = 2
        mat[0]=1
    elif Type == "B":
        for i in range(n):
            if i <n-1:
                mat[(n+1)*i-1] = -1
                mat[(n+1)*i] = 2
                mat[(n+1)*i+1]=-1
            else:
                mat[(n+1)*i-1] = -1
                mat[(n+1)*i] = 2
        mat[0]=1
        mat[n*n-1]=1
    elif Type == "C":
        for i in range(n):
            if i <n-1:
                mat[(n+1)*i-1] = -1
                mat[(n+1)*i] = 2
                mat[(n+1)*i+1]=-1
            else:
                mat[(n+1)*i-1] = -1
                mat[(n+1)*i] = 2
        mat[n-1]=-1
        mat[n*(n-1)]=-1
    else : 
        print("Please check input!")
        
        
    mat = mat.reshape(n,n)
    return mat

In [3]:
x =KTBC("K",5)


In [4]:
print(alg.det(x))  # 行列式

6.0


In [5]:
def Ktbc(Type,n):  # 更改后的计算程序，大幅减少了行数
    mat = np.zeros(n*n)
    for i in range(n):
        if i <n-1:
            mat[(n+1)*i-1] = -1
            mat[(n+1)*i] = 2
            mat[(n+1)*i+1]=-1
        else:
            mat[(n+1)*i-1] = -1
            mat[(n+1)*i] = 2
    if Type == "K" or Type == "k" : pass
    elif Type == "T"or Type =="t": mat[0]=1
    elif Type == "B"or Type =="b": mat[0],mat[n*n-1]=1,1
    elif Type == "C" or Type =="c": mat[n-1],mat[n*(n-1)]= -1,-1
    else :
        print("Please check input")
        raise ValueError
    mat = mat.reshape(n,n)
    return mat

In [6]:
x1 = Ktbc("k",3)
print(x1)
x2 = Ktbc("b",3)
print(x2)
x3 = Ktbc("c",3)
print(x3)
x4 =Ktbc("k",3)
print(x4)

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]
[[ 1. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]
[[ 2. -1. -1.]
 [-1.  2. -1.]
 [-1. -1.  2.]]
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


In [7]:
 print (alg.det(x1))

4.0


In [8]:
xxx = np.eye(4,k=1)*-1+np.eye(4)*2+np.eye(4,k=-1)*-1 # numpy and matlab command are mostly the same
xxx

array([[ 2., -1.,  0.,  0.],
       [-1.,  2., -1.,  0.],
       [ 0., -1.,  2., -1.],
       [ 0.,  0., -1.,  2.]])

In [9]:
yyy = alg.toeplitz([2,-1,0,0],[2,-1,0,0])
yyy

array([[ 2, -1,  0,  0],
       [-1,  2, -1,  0],
       [ 0, -1,  2, -1],
       [ 0,  0, -1,  2]])

In [10]:
p,l,u = alg.lu(yyy) # scipy 中的
print(p) 
print(l)
print(u)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.          0.          0.          0.        ]
 [-0.5         1.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.        ]
 [ 0.          0.         -0.75        1.        ]]
[[ 2.         -1.          0.          0.        ]
 [ 0.          1.5        -1.          0.        ]
 [ 0.          0.          1.33333333 -1.        ]
 [ 0.          0.          0.          1.25      ]]


In [11]:
# Practice 1.3 
# p1
A = Ktbc("K",4)
for N in range(3,6):
    x = Ktbc("K",N)
    print("determinant of K(%d)is%f"%(N,alg.det(x)))
    p,l,u = alg.lu(x)
    print("lower triangle of K(",N,")is\n" ,l )
    print("upper triangle of K(",N,")is\n" ,u )
    DD =np.mat(np.identity(N)*np.diag(u))
    print(DD)
    print(np.dot(alg.inv(DD),u)) # use np.dot (matrix multiply)


determinant of K(3)is4.000000
lower triangle of K( 3 )is
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]]
upper triangle of K( 3 )is
 [[ 2.         -1.          0.        ]
 [ 0.          1.5        -1.        ]
 [ 0.          0.          1.33333333]]
[[ 2.          0.          0.        ]
 [ 0.          1.5         0.        ]
 [ 0.          0.          1.33333333]]
[[ 1.         -0.5         0.        ]
 [ 0.          1.         -0.66666667]
 [ 0.          0.          1.        ]]
determinant of K(4)is5.000000
lower triangle of K( 4 )is
 [[ 1.          0.          0.          0.        ]
 [-0.5         1.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.        ]
 [ 0.          0.         -0.75        1.        ]]
upper triangle of K( 4 )is
 [[ 2.         -1.          0.          0.        ]
 [ 0.          1.5        -1.          0.        ]
 [ 0.          0.          1.33333333 -1.        

In [12]:
print(np.diag(A))


[ 2.  2.  2.  2.]


In [17]:
alg.inv(A)*5


array([[ 4.,  3.,  2.,  1.],
       [ 3.,  6.,  4.,  2.],
       [ 2.,  4.,  6.,  3.],
       [ 1.,  2.,  3.,  4.]])