In [1]:
import numpy as np
from scipy.linalg import lu
K = np.mat([[1,1,0],[1,1,1],[0,1,1]])
print(K)
u = np.mat([1,2,3]).reshape(3,1)
print(u)

[[1 1 0]
 [1 1 1]
 [0 1 1]]
[[1]
 [2]
 [3]]


In [2]:
f = K*u
print (f)


[[3]
 [6]
 [5]]


In [3]:
p,l,u = lu(K)

In [4]:
x1 = np.dot(p,l)
x2 = np.dot(x1,u)                                

x2

array([[ 1.,  1.,  0.],
       [ 1.,  1.,  1.],
       [ 0.,  1.,  1.]])

In [11]:
def ff1(t):
    return np.e**(-2*t)

In [12]:
print (ff1(0))

1.0


In [16]:
from scipy.optimize import fsolve
print(fsolve(ff1,0))

[ 138.05003965]


D:\Python36\lib\site-packages\scipy\optimize\minpack.py:161: RuntimeWarning: The number of calls to function has reached maxfev = 400.
  warnings.warn(msg, RuntimeWarning)
